AWSTemplateFormatVersion: 2010-09-09
Resources:
  dopt######:
    Type: 'AWS::EC2::DHCPOptions'
    Properties:
      Tags:
        - Key: Name
          Value: test.local
      DomainName: test.local
      DomainNameServers:
        - 10.65.5.4
        - 10.65.5.1
  dop########:
    Type: 'AWS::EC2::DHCPOptions'
    Properties:
      Tags:
        - Key: Name
          Value: dev.local
      DomainName: dev.local
      DomainNameServers:
        - 10.65.5.4
        - 10.65.5.1
  dopt######:
    Type: 'AWS::EC2::DHCPOptions'
    Properties:
      Tags:
        - Key: Name
          Value: Domain.Local
      DomainName: domain.local
      DomainNameServers:
        - 10.1.1.9
        - 10.1.1.6
      NtpServers:
        - 10.1.1.9
        - 10.1.1.6
  dopt####:
    Type: 'AWS::EC2::DHCPOptions'
    Properties:
      Tags:
        - Key: Name
          Value: money.com
      DomainName: money.com
      DomainNameServers:
        - 10.6.6.1
        - 10.1.2.6
  dopt###:
    Type: 'AWS::EC2::DHCPOptions'
    Properties:
      Tags:
        - Key: Name
          Value: domain.local
      DomainName: domain.local
      DomainNameServers:
        - 10.1.1.9
        - 10.1.1.6
  dopt#####:
    Type: 'AWS::EC2::DHCPOptions'
    Properties:
      Tags:
        - Key: Name
          Value: test.local
      DomainName: test.local
      DomainNameServers:
        - 10.1.1.29
        - 10.1.1.26
        - 10.21.1.10
  dopt3####:
    Type: 'AWS::EC2::DHCPOptions'
    Properties:
      Tags:
        - Key: Name
          Value: Amazon DNS
      DomainName: ec2.internal
      DomainNameServers:
        - AmazonProvidedDNS
Description: DHCP Option Sets
